### PR TITLE
Do not expect KUBECONFIG to be always set

### LINKED ISSUE #40: Changing namespace takes two attempts
**Describe the bug**
When I change the namespace via `kn` (Fish), it takes two attempts to succeed instead of one.

**Steps to reproduce**
```shell
# Check if $KUBECONFIG is set
→ set -q KUBECONFIG && echo Set || echo Not set
Not set

# Try to change the namespace
→ kn strimzi && echo OK || echo Fail
Fail

# Again, check if $KUBECONFIG is set
→ set -q KUBECONFIG && echo Set || echo Not set
Set

# Print $KUBECONFIG value
→ echo $KUBECONFIG

# Again, try to change the namespace
→ kn strimzi && echo OK || echo Fail
OK
```

**Expected behavior**
It should take a single attempt to change the namespace.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Version: 1.2.8 and ea51d8c82ee28a9b0717ddaa799f46d54adcff61

**Additional context**
It looks like `kubesess` expects `$KUBECONFIG` to be always set. The first failing attempt sets it to an empty string, and the second one succeeds.

Here's what it looks like with additional details:
```shell
RUST_BACKTRACE=1 kubesess namespace -c
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config.rs:110:60
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
             at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/option.rs:775:21
   4: kubesess::config::get_current_session
             at /Users/smorozov/Projects/kubesess/src/config.rs:110:34
   5: kubesess::modes::namespace
             at /Users/smorozov/Projects/kubesess/src/modes.rs:67:18
   6: kubesess::Mode::invoke
             at /Users/smorozov/Projects/kubesess/src/main.rs:43:32
   7: kubesess::main
             at /Users/smorozov/Projects/kubesess/src/main.rs:57:5
   8: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by morozov**
Fixes #40.

### CODE REVIEW

**Review by Ramilito — APPROVED** [review]

**Comment by morozov** [comment]
Another issue I stumbled upon is that this call: https://github.com/Ramilito/kubesess/blob/75f073108c6b6d00e4afd8026714500886601225/src/config.rs#L95

Can panic if the `open()` fails (e.g. because the file doesn't exist or it's not readable by the current user). This is way less likely than the issue in question but it may still make sense to handle it properly.

**Comment by Ramilito** [comment]
hmm good point, what would you suggest we do there, create the file?

**Comment by morozov** [comment]
I would just exit with a meaningful error message. Ideally, the one returned by the operating system. E.g. "No such file or directory":
```
$ cat non-existing-file.txt
cat: non-existing-file.txt: No such file or directory
```
The shell wrappers should properly interpret the non-zero exit code and passthrough STDERR to the terminal.

**Comment by Ramilito** [comment]
That's a good suggestion, I created an issue for it!

**Pull request merged**
